### ISSUE TITLE
Crashes after breaking 2 blocks

### ISSUE THREAD

**Issue by laurits-mumberg** [OpenPrograms/OpenPrograms.ru#4]
![image](https://user-images.githubusercontent.com/15343686/50388358-f5231180-0713-11e9-8169-60f1d404a796.png)

The robot breaks two blocks and then crashes
EDIT:
Meant to post this at geomine.lua

**Comment by Fingercomp** [comment]
I have pushed a commit that may fix the error. Does the problem still happen on the newer version?

---

Also, this is how the arguments should be passed to the program:

```
geomine 1 5
```

Note that the numbers are separated not with a comma but with a space.
