### ISSUE TITLE
openglasses 2 compatability issue

### ISSUE THREAD

**Issue by aerogers** [OpenPrograms/OpenPrograms.ru#5]
It doesn't seem to work with open glasses 2.  It seems og2 doesn't have the dot 3d function and throws errors when attempting to use it.  I've attempted to use the text 3d method instead.

**Comment by Fingercomp** [comment]
Yeah. When the program was written, OpenGlasses 2 didn't even exist. And, compared to OG 1, they've changed basically every single API method they could, so it's no wonder the program doesn't work with it. I don't think I can contact the original author now, so I'll try fixing it myself. It doesn't seems hard, anyway.
